#!/bin/bash -e
# -e: Exit immediately if a command exits with a non-zero status.

prefix="/usr/local"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
pkgincludedir="${prefix}/include/biogeme"
pkglibdir="${exec_prefix}/lib/biogeme"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
pkgdatadir="${datarootdir}/biogeme"
versionsuffix=""
pythonbin="/usr/local/bin/python3.4"

if [ $# -ne 1 ]; then
  echo 'One argument is required: the name of the data file.'
  exit -1
fi
m=$1 
if [ ! -f "${m}" ]
then
  echo "File ${m} not found!"
  exit
fi
"${pythonbin}" "${pkgdatadir}/biopreparedata.py" "${m}"

