#!/bin/bash -e
# -e: Exit immediately if a command exits with a non-zero status.

prefix="/usr/local"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
pkgincludedir="${prefix}/include/biogeme"
pkglibdir="${exec_prefix}/lib/biogeme"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
pkgdatadir="${datarootdir}/biogeme"
versionsuffix=""

export PYTHONPATH=.:"${pkgdatadir}":$PYTHONPATH
export LD_LIBRARY_PATH="${pkglibdir}":$LD_LIBRARY_PATH

echo 'This is biogeme (pythonbiogeme) 2.7b'
# Number of arguments
if [ $# -ne 2 ]; then
  echo 'Two arguments are required: the name of the python file (without extension) and the name of the data file.'
  exit -1
fi
p=$1 
d=$2 

if [ ! -f "${p}.py" ]
then
  echo "File ${p}.py not found!"
  exit
fi

if [ ! -f "$d" ]
then
  echo "File $d not found!"
  exit
fi

"${bindir}/pybiogeme_static${versionsuffix}" "$p" "$d"
echo 'Done'
