CVS
patAbsTime.h
patAlgorithms.h
patClass.h
patCompare.h
patCompare.h~
patConst.h
patDisplay.h
patErrFileNotFound.h
patErrMiscError.h
patErrNullPointer.h
patErrOutOfRange.h
patError.h
patFileExists.h
patFixedPointAlgorithms.h
patFixedPointAlgorithms.h~
patFunction.h
patFunctionAuto.h
patFunctionAuto.h~
patHybridMatrix.h
patMath.h
patMatrix.h
patMatrix.h~
patOutput.h
patOutput.h~
patPointer.h
patRandom.h
patSymmMatrix.h
patSymmZeroDiagMatrix.h
patType.h
patVariables.h
